CREATE TABLE `PROFILES` (
  `PROFILE_ID` INTEGER(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROFILENAME` VARCHAR(20),
  `FIRSTNAME` VARCHAR(40),
  `LASTNAME` VARCHAR(40),
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATED` datetime NOT NULL,
  PRIMARY KEY (`PROFILENAME`),
  UNIQUE(`PROFILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


INSERT INTO PROFILES(PROFILENAME,FIRSTNAME,LASTNAME,LAST_UPDATED) VALUES("A1", "A1F","A1L",NOW());
INSERT INTO PROFILES(PROFILENAME,FIRSTNAME,LASTNAME,LAST_UPDATED) VALUES("A2", "A2F","A2L",NOW());
INSERT INTO PROFILES(PROFILENAME,FIRSTNAME,LASTNAME,LAST_UPDATED) VALUES("A3", "A3F","A3L",NOW());
INSERT INTO PROFILES(PROFILENAME,FIRSTNAME,LASTNAME,LAST_UPDATED) VALUES("A4", "A4F","A4L",NOW());
INSERT INTO PROFILES(PROFILENAME,FIRSTNAME,LASTNAME,LAST_UPDATED) VALUES("A5", "A5F","A5L",NOW());
INSERT INTO PROFILES(PROFILENAME,FIRSTNAME,LASTNAME,LAST_UPDATED) VALUES("A6", "A6F","A6L",NOW());
INSERT INTO PROFILES(PROFILENAME,FIRSTNAME,LASTNAME,LAST_UPDATED) VALUES("A7", "A7F","A7L",NOW());